import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Athlete profile table - extends users with athlete-specific data
 */
export const athletes = mysqlTable("athletes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  dateOfBirth: varchar("dateOfBirth", { length: 10 }),
  heightCm: int("heightCm"),
  weightKg: int("weightKg"),
  position: varchar("position", { length: 50 }),
  preferredFoot: mysqlEnum("preferredFoot", ["left", "right", "both"]),
  clubName: varchar("clubName", { length: 255 }),
  bio: text("bio"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Athlete = typeof athletes.$inferSelect;
export type InsertAthlete = typeof athletes.$inferInsert;

/**
 * Club profile table - extends users with club-specific data
 */
export const clubs = mysqlTable("clubs", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  clubName: varchar("clubName", { length: 255 }).notNull(),
  city: varchar("city", { length: 255 }),
  state: varchar("state", { length: 2 }),
  description: text("description"),
  logoUrl: varchar("logoUrl", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Club = typeof clubs.$inferSelect;
export type InsertClub = typeof clubs.$inferInsert;

/**
 * Videos table - stores metadata about uploaded videos
 */
export const videos = mysqlTable("videos", {
  id: int("id").autoincrement().primaryKey(),
  athleteId: int("athleteId").notNull(),
  fileUrl: varchar("fileUrl", { length: 255 }).notNull(),
  fileSizeMb: int("fileSizeMb"),
  durationSeconds: int("durationSeconds"),
  uploadDate: timestamp("uploadDate").defaultNow().notNull(),
  processingStatus: mysqlEnum("processingStatus", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  processingError: text("processingError"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Video = typeof videos.$inferSelect;
export type InsertVideo = typeof videos.$inferInsert;

/**
 * KPIs table - stores performance metrics generated by vision processing
 */
export const kpis = mysqlTable("kpis", {
  id: int("id").autoincrement().primaryKey(),
  videoId: int("videoId").notNull().unique(),
  athleteId: int("athleteId").notNull(),
  avgSpeedKmh: int("avgSpeedKmh"),
  maxSpeedKmh: int("maxSpeedKmh"),
  ballTouches: int("ballTouches"),
  passesAttempted: int("passesAttempted"),
  passesCompleted: int("passesCompleted"),
  passAccuracyPercent: int("passAccuracyPercent"),
  sprintsCount: int("sprintsCount"),
  avgAcceleration: int("avgAcceleration"),
  distanceCoveredM: int("distanceCoveredM"),
  intensityScore: int("intensityScore"),
  skeletonLandmarks: text("skeletonLandmarks"),
  generatedAt: timestamp("generatedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type KPI = typeof kpis.$inferSelect;
export type InsertKPI = typeof kpis.$inferInsert;

/**
 * Athlete rankings cache - aggregated scores for quick ranking queries
 */
export const athleteRankings = mysqlTable("athleteRankings", {
  id: int("id").autoincrement().primaryKey(),
  athleteId: int("athleteId").notNull().unique(),
  overallScore: int("overallScore"),
  speedScore: int("speedScore"),
  dribblingScore: int("dribblingScore"),
  accuracyScore: int("accuracyScore"),
  totalVideos: int("totalVideos").default(0).notNull(),
  avgIntensity: int("avgIntensity"),
  lastUpdated: timestamp("lastUpdated").defaultNow().onUpdateNow().notNull(),
});

export type AthleteRanking = typeof athleteRankings.$inferSelect;
export type InsertAthleteRanking = typeof athleteRankings.$inferInsert;

/**
 * Club follows - relationship between clubs and athletes they're watching
 */
export const clubFollows = mysqlTable("clubFollows", {
  id: int("id").autoincrement().primaryKey(),
  clubId: int("clubId").notNull(),
  athleteId: int("athleteId").notNull(),
  followedAt: timestamp("followedAt").defaultNow().notNull(),
});

export type ClubFollow = typeof clubFollows.$inferSelect;
export type InsertClubFollow = typeof clubFollows.$inferInsert;
